version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: shopping_cart_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: shopping_cart
      MYSQL_USER: "123456"
      MYSQL_PASSWORD: "123456"
  phpmyadmin:
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
